# ============================================================
# Dockerfile - Microservicio
# ============================================================
FROM eclipse-temurin:21-jdk-alpine AS build

RUN apk add --no-cache maven

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B -q

COPY src ./src
RUN mvn package -DskipTests -B -q

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

# El puerto cambia según el microservicio (ej. 8087 para notificaciones)
EXPOSE 8086

ENTRYPOINT ["java", "-jar", "app.jar"]
