spring.application.name=resena
server.port=8088

# Base de Datos
spring.datasource.url=jdbc:mysql://mysql:3306/db_resena?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=resena-service
eureka.instance.instance-id=${spring.application.name}:${server.port}
