server:
  port: 8090

spring:
  application:
    name: APIGateway-server
  cloud:
    gateway:
      routes:
        - id: ruta-usuarios
          uri: lb://USUARIOSMICRO
          predicates:
            - Path=/usuarios,/usuarios/**

        - id: ruta-catalogo
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/libros,/libros/**

        - id: ruta-carrito
          uri: lb://CARRITO
          predicates:
            - Path=/carrito,/carrito/**

        - id: ruta-prestamo
          uri: lb://PRESTAMO
          predicates:
            - Path=/prestamos,/prestamos/**

        - id: ruta-envio
          uri: lb://ENVIO
          predicates:
            - Path=/envios,/envios/**

        - id: ruta-pago
          uri: lb://PAGO
          predicates:
            - Path=/pagos,/pagos/**

        - id: ruta-notificaciones
          uri: lb://NOTIFICACIONES
          predicates:
            - Path=/notificaciones,/notificaciones/**

        - id: ruta-resena
          uri: lb://RESENA
          predicates:
            - Path=/resenas,/resenas/**

        - id: ruta-reporte
          uri: lb://REPORTE
          predicates:
            - Path=/reportes,/reportes/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG