# Sigue sin registrarse en sí mismo, pero mapeamos las rutas internas de Docker
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Cambiamos localhost por el nombre del contenedor asignado en el docker-compose
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=eureka-server

# Mantenemos las configuraciones de desarrollo y logs dentro del contenedor
eureka.server.enable-self-preservation=false
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO