# Nombre del servidor
spring.application.name=eureka-server
server.port=8761

# CONFIGURACIÓN CRÍTICA PARA EUREKA
# Como este ES el servidor, no debe intentar registrarse en sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL de servicio (apuntando a sí mismo en Docker)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=eureka-server

# Desactiva la auto-preservación (recomendado para desarrollo/exámenes )
eureka.server.enable-self-preservation=false
